### ISSUE TITLE
I can not find ps3netsrv on "./bin/packages/{yourPlatform}/ps3netsrv_feed/"

### ISSUE THREAD

**Issue by lingandken** [jhonathanc/ps3netsrv-openwrt#1]
I can not find ps3netsrv on "./bin/packages/{yourPlatform}/ps3netsrv_feed/”

**Comment by jhonathanc** [comment]
Did it compile without any errors on console log? What's your target platform?

**Comment by lingandken** [comment]
Yes nothing wrong



发自我的iPhone


------------------ Original ------------------

**Comment by jhonathanc** [comment]
What's your target platform? You need to replace "{yourPlatform}" with yours target platform.

**Comment by lingandken** [comment]
K2P MT7621 Can you help me make a ipk?



发自我的iPhone


------------------ Original ------------------

**Comment by jhonathanc** [comment]
The ipk should be on "./bin/packages/mt7621/ps3netsrv_feed/".

**Comment by lingandken** [comment]
I only downloaded the SDK for this platform But the folder is empty after&nbsp;Compile



发自我的iPhone


------------------ Original ------------------

**Comment by lingandken** [comment]
I checked the folder several times and recompiled several times

发自我的iPhone


------------------ Original ------------------

**Comment by jhonathanc** [comment]
Sorry, I did a mistake on last repy. The ipk should be on "./bin/packages/ramips/ps3netsrv_feed/". If it's not, I will help you building that.

**Comment by lingandken** [comment]
Thank you very much&nbsp;I have used the search function to find the entire openwrt folder, but still no

发自我的iPhone


------------------ Original ------------------

**Comment by jhonathanc** [comment]
This is the IPK you asked:
https://github.com/jhonathanc/ps3netsrv/releases/download/20190630/ps3netsrv-mbedtls-mipsel_24kc.ipk

I edited the instructions, because the "clean' command was deleting the ipk. Sorry about that.

You are welcome.
