### ISSUE TITLE
Feeds Install Permission Denied

### ISSUE THREAD

**Issue by 2018-lonely-droid** [jhonathanc/ps3netsrv-openwrt#2]
Hi, 
This may be the wrong place to paste this, but I need your help.. I have used your tool before (thank you so much) on another platform, but this time I am trying to build the package for ar71xx on 19.07.2

When I extract the SDK to my download folder... or any folder and try to run:

./scripts/feeds update -a
./scripts/feeds install -a

I get 
bash: ./scripts/feeds: Permission denied

When I try the same commands in root with
sudo su

I still get the permission denied. 
I have been able to brute force past this with chmod 777 command, but then I get errors in that there are circular dependencies and extra packages not included in the feeds and the make file requires. 

I have tried running the commands on elemetary os, linux mint, and lubuntu on different machines in different folders and it is always the same errors.

I am new to making packages for openwrt but have been using openwrt for a few years. 

Thank you for your tool and your help.

**Comment by jhonathanc** [comment]
Sorry about being so late to reply. If you are still trying to build it, check my github action, it has the mips_24kc binary used on ar71xx and ath79 (download the binary on "Artifacts" section):

https://github.com/jhonathanc/ps3netsrv-openwrt/actions/runs/2626652436

If you want to build it by yourself, check the "main.yml" used to build the artifacts, it's a "cake recipe" with every step adopted to build it on a "clean" linux distro.
